=== zekun-li/toponym_detection/spatialml/package/common_files/dtd/aif.dtd
<!-- 

A DTD for ATLAS Interchange Format [AIF], a means of interchanging
annotations. AIF has been developed following joint discussions with
Bird (LDC), Day (MITRE), Garofolo (NIST), Henderson (MITRE) and Laprun
(NIST).

Current maintainer: Chris Laprun [ chris.laprun@nist.gov ]

$Id: aif.dtd,v 1.22 2002/09/13 19:32:14 chris Exp $

-->

<!-- ** PARAMETER ENTITIES ** -->
<!ENTITY % MetadataDef SYSTEM "metadata.dtd"> %MetadataDef;

<!ENTITY % FeatureData "(Feature  | Parameter)+">

<!ENTITY % containerAtt "
    containedType NMTOKEN   #REQUIRED">

<!ENTITY % refAtt "    
    xlink:type    CDATA             #FIXED    'simple'
    xlink:href    CDATA             #REQUIRED
    role          NMTOKEN           #REQUIRED">

<!ENTITY % idAtt "
    id          ID       #REQUIRED
    type        NMTOKEN  #REQUIRED">

<!-- ** ELEMENTS ** -->
<!ELEMENT Corpus ( Metadata, (SimpleSignal | SignalGroup)*, AnchorSet*, RegionSet*, Analysis*)>
<!ATTLIST Corpus
    %idAtt;
    AIFVersion  CDATA    #FIXED    "1.1"
    xmlns       CDATA    #FIXED    "http://www.nist.gov/speech/atlas"
    xmlns:xlink CDATA    #FIXED    "http://www.w3.org/1999/xlink"
    schemeLocation CDATA #REQUIRED
>

<!ELEMENT Analysis ( Metadata?, AnnotationSet* )>
<!ATTLIST Analysis
    %idAtt;
    role        NMTOKEN  #REQUIRED
>

<!ELEMENT AnchorSet ( Anchor* )>
<!ATTLIST AnchorSet %containerAtt;>

<!ELEMENT AnnotationSet ( Annotation* )>
<!ATTLIST AnnotationSet %containerAtt;>

<!ELEMENT RegionSet ( Region* )>
<!ATTLIST RegionSet %containerAtt;>

<!ELEMENT SimpleSignal ( body )> <!-- changed Metadata? to body -->
<!ATTLIST SimpleSignal
    %idAtt;
    mimeClass   CDATA      #REQUIRED
    mimeType    CDATA      #REQUIRED
    encoding    CDATA      #REQUIRED
    xlink:type  CDATA      #FIXED        "simple"
    xlink:href  CDATA      #REQUIRED
    track       NMTOKEN    "ALL"
>

<!-- added body -->
<!ELEMENT body ( #PCDATA )>
<!ATTLIST body
    encoding    CDATA      #REQUIRED
>

<!ELEMENT SignalGroup ( Metadata?, SignalRef+ )>
<!ATTLIST SignalGroup %idAtt;>

<!ELEMENT Annotation ( (RegionRef | RegionDefinedByChildren), (Content | ContentDefinedByChildren), Children* )>
<!ATTLIST Annotation %idAtt;>

<!ELEMENT Content ( RegionRef? , (%FeatureData;)? )>
<!ATTLIST Content
    type       NMTOKEN    #REQUIRED
>

<!ELEMENT Feature %FeatureData;>
<!ATTLIST Feature
    role        NMTOKEN    #REQUIRED
    type        NMTOKEN    #REQUIRED     
>

<!ELEMENT Region 
    ( (AnchorRef | RegionRef | AnnotationRef)*, 
    (AnchorRefSet | RegionRefSet | AnnotationRefSet)* )>
<!ATTLIST Region %idAtt;>

<!ELEMENT Anchor ( Parameter+, SignalRef )>
<!ATTLIST Anchor %idAtt;>

<!ELEMENT Parameter ( #PCDATA )>
<!ATTLIST Parameter
    type        NMTOKEN     #REQUIRED 
    role        NMTOKEN     #REQUIRED    
    unit        NMTOKEN     #REQUIRED
>

<!ELEMENT AnchorRefSet ( AnchorRef* )>
<!ATTLIST AnchorRefSet %containerAtt;>

<!ELEMENT AnnotationRefSet ( AnnotationRef* )>
<!ATTLIST AnnotationRefSet %containerAtt;>

<!ELEMENT RegionRefSet ( RegionRef* )>
<!ATTLIST RegionRefSet %containerAtt;>

<!ELEMENT Children ( AnnotationRef* )>
<!ATTLIST Children %containerAtt;
  role        NMTOKEN #REQUIRED
>

<!ELEMENT ContentDefinedByChildren EMPTY>
<!ATTLIST ContentDefinedByChildren
   withContainedType NMTOKEN #REQUIRED
   withRole          NMTOKEN #REQUIRED
>

<!ELEMENT RegionDefinedByChildren EMPTY>
<!ATTLIST RegionDefinedByChildren
   withContainedType NMTOKEN #REQUIRED
   withRole          NMTOKEN #REQUIRED
>

<!ELEMENT RegionRef EMPTY>
<!ATTLIST RegionRef %refAtt;>

<!ELEMENT AnchorRef EMPTY>
<!ATTLIST AnchorRef %refAtt;>

<!ELEMENT AnnotationRef EMPTY>
<!ATTLIST AnnotationRef %refAtt;>

<!ELEMENT SignalRef EMPTY>
<!ATTLIST SignalRef %refAtt;>

=== zekun-li/toponym_detection/spatialml/mitre_spatialml_v1/data/MARKETVIEW_20050217.2115.aif.xml
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE Corpus SYSTEM "http://www.nist.gov/speech/atlas/aif.dtd">

<Corpus xmlns="http://www.nist.gov/speech/atlas" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://www.ukoln.ac.uk/interop-focus/activities/z3950/int_profile/bath/draft/stable1.html" id="Cor13" AIFVersion="1.1" type="spatialml" schemeLocation="http://callisto.mitre.org/maia/spatialml.maia.xml">
  <Metadata/>
  <SimpleSignal id="Sig13" type="text" mimeClass="text" mimeType="sgml" xlink:href="MARKETVIEW_20050217.2115.sgm" encoding="UTF-8" track="ALL" xlink:type="simple">
    <body encoding="Base64">PERPQz4NCg0KIE1BUktFVFZJRVdfMjAwNTAyMTcuMjExNSANCiBXRUIgVEVYVCANCiAyMDA1LTAyLTE3VDIxOjE1OjAwIA0KDQoNCkFuIEFpcmxpbmUgUGFzc2VuZ2VyJ3MgQmlsbCBvZiBSaWdodHM/DQoNCjxURVhUPg0KDQoNCiBCeXJuZSANCiAyMDA1LTAyLTE3VDIxOjE1OjAwIA0KSGFzIHRoZSBFVSBvbmNlIGFnYWluIGxvc3QgaXRzIG1pbmQ/IFRoZSBvbmUgaW5kdXN0cnkgaW4gd2hpY2ggRXVyb3BlDQppbmNvbnRyb3ZlcnRpYmx5IGJlYXRzIHRoZSBVUyBpcyB0aGVpciBhdmlhdGlvbiBpbmR1c3RyeSAsIHRoYW5rcyBtYWlubHkNCnRvIHRoZSBmYWN0IHRoYXQgdGhlaXIgbGF3bWFrZXJzIGhhdmUgbGVmdCB0aGUgb3BlcmF0aW9uIG9mIHRoZSBpbmR1c3RyeQ0KdXAgdG8gdGhlIHBlb3BsZSB3aG8gb3duIGl0LCBhbmQgbGVmdCBwYXNzZW5nZXIncyByaWdodHMgaW4gdGhlIGhhbmRzIG9mDQpjaG9vc3kgcGFzc2VuZ2Vycy4gQW5kIG5vdyB0aGV5J3JlIHJlYWR5IHRvICdmaXgnIHRoYXQgd2l0aCBhIG5ldw0KcGFja2FnZSBvZiBpbGwtYWR2aXNlZCBydWxlcyBjb21wbGV0ZWx5IGNoYW5naW5nIHRoZSBuYXR1cmUgb2YgYWlybGluZXMNCi4gQmVmb3JlLCBhIHBvdGVudGlhbCBjdXN0b21lciBjb3VsZCBjaG9vc2UgYmV0d2VlbiBhIGNvc3ksIG5lYXItY2VydGFpbg0KcmlkZSBmcm9tIGFuIGV4cGVuc2l2ZSBjb21wYW55IG9yIGEgaHVzdGxlZCwgdW5jb21mb3J0YWJsZSwgYW5kIGFic3VyZGx5DQpjaGVhcCBvbmUgZnJvbSBhIHNtYWxsZXIgY29tcGV0aXRvci4gQW5kIG5vdz8gTm90IGEgY2hhbmNlLg0KDQo8L1RFWFQ+DQoNCg0KPC9ET0M+</body>
  </SimpleSignal>
  <AnchorSet containedType="text-point">
    <Anchor id="Anc28" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">214</Parameter>
      <SignalRef xlink:href="#Sig13" role="text" xlink:type="simple"/>
    </Anchor>
    <Anchor id="Anc29" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">220</Parameter>
      <SignalRef xlink:href="#Sig13" role="text" xlink:type="simple"/>
    </Anchor>
    <Anchor id="Anc30" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">249</Parameter>
      <SignalRef xlink:href="#Sig13" role="text" xlink:type="simple"/>
    </Anchor>
    <Anchor id="Anc31" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">251</Parameter>
      <SignalRef xlink:href="#Sig13" role="text" xlink:type="simple"/>
    </Anchor>
  </AnchorSet>
  <RegionSet containedType="link-subordinates"/>
  <RegionSet containedType="path-subordinates"/>
  <RegionSet containedType="text-extent">
    <Region id="Reg12" type="text-extent">
      <AnchorRef xlink:href="#Anc29" role="end" xlink:type="simple"/>
      <AnchorRef xlink:href="#Anc28" role="start" xlink:type="simple"/>
    </Region>
    <Region id="Reg13" type="text-extent">
      <AnchorRef xlink:href="#Anc31" role="end" xlink:type="simple"/>
      <AnchorRef xlink:href="#Anc30" role="start" xlink:type="simple"/>
    </Region>
  </RegionSet>
  <Analysis id="Ana73" type="link-extent-set" role="link-extent-set">
    <AnnotationSet containedType="link-extent"/>
  </Analysis>
  <Analysis id="Ana74" type="link-set" role="link-set">
    <AnnotationSet containedType="LINK"/>
  </Analysis>
  <Analysis id="Ana75" type="path-extent-set" role="path-extent-set">
    <AnnotationSet containedType="path-extent"/>
  </Analysis>
  <Analysis id="Ana76" type="path-set" role="path-set">
    <AnnotationSet containedType="PATH"/>
  </Analysis>
  <Analysis id="Ana77" type="place-set" role="place-set">
    <AnnotationSet containedType="PLACE">
      <Annotation id="Ann12" type="PLACE">
        <RegionRef xlink:href="#Reg12" role="text-extent" xlink:type="simple"/>
        <Content type="place-content">
          <Parameter type="string" unit="NULL_UNIT" role="continent">EU</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="description"/>
          <Parameter type="string" unit="NULL_UNIT" role="form">NAM</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="gazref">IGDB:30064878</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="id">Pl-1</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="nonLocUse"/>
          <Parameter type="string" unit="NULL_UNIT" role="type">CONTINENT</Parameter>
        </Content>
      </Annotation>
      <Annotation id="Ann13" type="PLACE">
        <RegionRef xlink:href="#Reg13" role="text-extent" xlink:type="simple"/>
        <Content type="place-content">
          <Parameter type="string" unit="NULL_UNIT" role="country">US</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="description"/>
          <Parameter type="string" unit="NULL_UNIT" role="form">NAM</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="gazref">IGDB:840</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="id">Pl-2</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="nonLocUse"/>
          <Parameter type="string" unit="NULL_UNIT" role="type">COUNTRY</Parameter>
        </Content>
      </Annotation>
    </AnnotationSet>
  </Analysis>
  <Analysis id="Ana78" type="signal-set" role="signal-set">
    <AnnotationSet containedType="SIGNAL"/>
  </Analysis>
</Corpus>

=== zekun-li/toponym_detection/spatialml/mitre_spatialml_v1/data/misc.kids.pregnancy_20050120.0404.aif.xml
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE Corpus SYSTEM "http://www.nist.gov/speech/atlas/aif.dtd">

<Corpus xmlns="http://www.nist.gov/speech/atlas" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://www.ukoln.ac.uk/interop-focus/activities/z3950/int_profile/bath/draft/stable1.html" id="Cor7" AIFVersion="1.1" type="spatialml" schemeLocation="http://callisto.mitre.org/maia/spatialml.maia.xml">
  <Metadata/>
  <SimpleSignal id="Sig7" type="text" mimeClass="text" mimeType="sgml" xlink:href="misc.kids.pregnancy_20050120.0404.sgm.sgml" encoding="UTF-8" track="ALL" xlink:type="simple">
    <body encoding="Base64">PERPQz4NCg0KIG1pc2Mua2lkcy5wcmVnbmFuY3lfMjAwNTAxMjAuMDQwNCANCiBXRUIgVEVYVCANCiAyMDA1LTAxLTIwVDA0OjA0OjAwIA0KDQoNClRoZSBQYWluIG9mIENoaWxkYmlydGgNCg0KPFRFWFQ+DQoNCg0KIEFubmEgTWMgDQogVGh1LCAyMCBKYW4gMjAwNSAxMDowNDoxOSArMDEwMCANCiBUaGUgUGFpbiBvZiBDaGlsZGJpcnRoIA0KDQpJIGhhdmUgMiBnaXJscyBhbHJlYWR5LCBuZWFybHkgOCBhbmQgNC41IHlycyBhbmQgSSBoYXZlIGFsd2F5cyBzYWlkIEkNCndpbGwgTkVWRVIgZm9yZ2V0IHRoZSBwYWluIG9mIGNoaWxkYmlydGguIEFiYnkgd2FzIGEgdHJ1ZSB3YXRlciBiaXJ0aA0KKDNrZyAtIG5vcm1hbCkgYW5kIHdpdGggRmlvbmEgSSB3YXMgZHJhZ2dlZCBvdXQgb2YgdGhlIHBvb2wgYWZ0ZXIgdGhlDQpoZWFkIGNyb3duZWQgKGd5bm8gaGFkIHdyaXR0ZW4gb24gbXkgbm90ZXMgc2hlIHdhcyA0a2cgKGxhcmdlKSBhbmQgdGhhdA0Kc2hlIHdhcyBub3QgdG8gYmUgYm9ybiBpbiB0aGUgd2F0ZXIgKGxvbmcgcGFpbmZ1bCBzdG9yeSEpIEkgY2FuIHN0aWxsDQpyZW1lbWJlciB0aG91Z2ggdGhlIHBhaW4gSSBmZWx0LiBJIGFtIG9uIHRoZSBsYXJnZSBzaWRlIGJ1dCBJIGFtIHNvDQp3b3JyaWVkIGFib3V0IGhvdyBJJ20gZ29pbmcgdG8gY29wZSB3aXRoIGEgbmF0dXJhbCBjaGlsZGJpcnRoIHdpdGhvdXQgYQ0KcG9vbCAobm90IGF2YWlsYWJsZSByb3VuZCBoZXJlKS4gSSd2ZSBzZWVuIHZpZGVvcyBhbmQgaGVhcmQgb2YgbGFkaWVzDQp3aG8gaGF2ZSAibWFuYWdlZCIgdGhlaXIgcGFpbiBjb250cm9sLiBIb3cgaW4gSGVhdmVucyBuYW1lIGNhbiB5b3UgZG8NCnRoYXQ/IEkndmUgYmVlbiB0aGVyZTsgSSBrbm93IHdoYXQgdGhlIHBhaW4gZmVlbHMgbGlrZSEhDQoNCkNhbiBhbnlvbmUgZ2l2ZSBtZSBhZHZpY2Ugb3IgbGV0IG1lIGtub3cgb2YgYW55IHRlY2huaXF1ZXMgd2hpY2ggbWlnaHQNCmJlIGFibGUgdG8gaGVscD8gVGhhbmtzIGluIGFkdmFuY2UuDQoNCkFubmEgTWMNCg0KDQoNCiBEYWdueSANCiBUaHUsIDIwIEphbiAyMDA1IDA2OjA4OjMwIC0wNTAwIA0KIFJlOiBUaGUgUGFpbiBvZiBDaGlsZGJpcnRoIA0KDQoNCiAgICANCg0KSWYgeW91IGRvbid0IGhhdmUgYW4gaW5zdGl0dXRpb25hbCB3YXRlciBiaXJ0aCBhdmFpbGFibGUsIGhhdmUgeW91DQpjb25zaWRlcmVkIGp1c3Qgc3RheWluZyBob21lPyBVbmFzc2lzdGVkIG9yIG1pZHdpZmUgYXR0ZW5kZWQ/DQoNCkkgdW5kZXJzdGFuZCBoeXBub2JpcnRoaW5nIGNhbiBiZSB2ZXJ5IGhlbHBmdWwuIEkgYW0gbm90IHB1cnN1aW5nIGl0DQpiZWNhdXNlIEkgd2FzIGFibGUgdG8gZ28gaW5zaWRlIHRoZSBwYWluIHRvIHRoZSBnb29kIHBsYWNlIHdpdGhvdXQgdHJhaW5pbmcsDQpsYXN0IHRpbWUuDQoNCkkgaGF2ZSBub3QgYmVlbiB0aGlua2luZyBtdWNoIGFib3V0IHRoZSBoYXJkIHBhcnQgb2YgbGFib3IgcHJpb3IgdG8gZ2V0dGluZw0Kc28gY2xvc2UuIE5vdyBJIHJlbWVtYmVyIGhvdyBpbnRlbnNlIGl0IGlzLiBJIHRoaW5rIEkgYW0gc3RpbGwgbG9va2luZw0KZm9yd2FyZCB0byBpdCBtb3JlIHRoYW4gZmVhcmluZyBpdCwgYnV0IGhleS4gSXQncyBhIHJlYWxseSBpbnRlbnNlLA0KdnVsbmVyYWJsZSB0aGluZy4NCg0KLS0gRGFnbnkNCg0KDQoNCiBXZWxjaGVzIA0KIFRodSwgMjAgSmFuIDIwMDUgMTU6NTI6NDkgR01UIA0KIFJlOiBUaGUgUGFpbiBvZiBDaGlsZGJpcnRoIA0KDQogICAgDQoNCklmIHlvdSBnbyBmb3IgYSBob21lIGJpcnRoIHlvdSBjYW4gcmVudCBhIGJpcnRoaW5nIHBvb2wuDQpJIHdvdWxkbid0IG5lY2Vzc2FyaXRseSBzYXkgdGhhdCB5b3Ugd2lsbCBoYXZlIGEgcmVwZWF0IGxhYm91ciENCk15IGZpcnN0IGxhYm91ciBJIHdhcyAzMCBob3VycyBhbmQgaGFkIGFuIGVwaWR1cmFsIGFmdGVyIDIyIGhvdXJzLg0KIzIgSSB3ZW50IGluIHNheWluZyAiZ2l2ZSBtZSB0aGUgZXBpZHVyYWwgYXNhcC1hbmQgbmV2ZXIgZ290IHRvIHRoZSBzdGF0ZQ0Kd2hlcmUgSSBmZWx0IHRoYXQgSSBuZWVkZWQgaXQuIE9ubHkgaGFkIHRlbnMgYW5kIGdhcy1hbmQtYWlyLiBTbyBkb24ndCBnaXZlDQp1cCBvbiB0aGUgaWRlYSBvZiBhIG5hdHVyYWwgYmlydGggYmVjYXVzZSBsYXN0IHRpbWUgd2FzIHBhaW5mdWwuDQpJIHRoaW5rIGRpZmZlcmVudCBwZW9wbGUvZGlmZmVyZW50IGxhYm91cnMgYXJlIGRpZmZlcmVudCwgc28ganVzdCBiZWNhdXNlDQpvbmUgcGVyc29uIHNheXMgIkkgZGlkICoqKiBhbmQgaXQgZGlkbid0IGh1cnQgYSBiaXQiIGRvZXNuJ3QgbWVhbiB0aGF0IGl0DQp3aWxsIHdvcmsgZm9yIHNvbWVvbmUgZWxzZSwgc28gZ29pbmcgaW4gd2l0aCBhIHNldCBvZiBzdWdnZXN0aW9ucywgYW5kIGJlaW5nDQpwcmVwYXJlZCB0byB0cnkgdGhlbSBhbmQgc2VlIHdoaWNoIGlzIHRoZSBiZXN0IGlzIHByb2JhYmx5IHRoZSBtb3N0IGhlbHBmdWwuDQooT2ggYW5kICJpdCBkaWRuJ3QgaHVydCBhIGJpdCIgaXMgdXN1YWxseSBoZWxwZWQgYnkgbXVtbXkgYW1uZXNpYSEhOy1QKQ0KRGViYmllDQoNCg0KPC9URVhUPg0KDQoNCjwvRE9DPg==</body>
  </SimpleSignal>
  <AnchorSet containedType="text-point"/>
  <RegionSet containedType="link-subordinates"/>
  <RegionSet containedType="path-subordinates"/>
  <RegionSet containedType="text-extent"/>
  <Analysis id="Ana37" type="link-extent-set" role="link-extent-set">
    <AnnotationSet containedType="link-extent"/>
  </Analysis>
  <Analysis id="Ana38" type="link-set" role="link-set">
    <AnnotationSet containedType="LINK"/>
  </Analysis>
  <Analysis id="Ana39" type="path-extent-set" role="path-extent-set">
    <AnnotationSet containedType="path-extent"/>
  </Analysis>
  <Analysis id="Ana40" type="path-set" role="path-set">
    <AnnotationSet containedType="PATH"/>
  </Analysis>
  <Analysis id="Ana41" type="place-set" role="place-set">
    <AnnotationSet containedType="PLACE"/>
  </Analysis>
  <Analysis id="Ana42" type="signal-set" role="signal-set">
    <AnnotationSet containedType="SIGNAL"/>
  </Analysis>
</Corpus>

=== zekun-li/toponym_detection/spatialml/package/ace_2005_spatialML/data/MARKETVIEW_20050209.1923.aif.xml
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE Corpus SYSTEM "http://www.nist.gov/speech/atlas/aif.dtd">

<Corpus xmlns="http://www.nist.gov/speech/atlas" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://www.ukoln.ac.uk/interop-focus/activities/z3950/int_profile/bath/draft/stable1.html" id="Cor389" AIFVersion="1.1" type="spatialml" schemeLocation="http://callisto.mitre.org/maia/spatialml.maia.xml">
  <Metadata/>
  <SimpleSignal id="Sig389" type="text" mimeClass="text" mimeType="sgml" xlink:href="MARKETVIEW_20050209.1923.sgml.sgml" encoding="UTF-8" track="ALL" xlink:type="simple">
    <body encoding="Base64">PERPQz4KCiBNQVJLRVRWSUVXXzIwMDUwMjA5LjE5MjMgCiBXRUIgVEVYVCAKIDIwMDUtMDItMDlUMTk6MjM6MDAgCgoKU2lyaXVzIFNhdGVsbGl0ZSAtLSBCcmlsbGlhbnQgUGxhbiwgb3IgR3Jhc3BpbmcgYXQgU3RyYXdzPwoKPFRFWFQ+CgoKIEJ5cm5lIAogMjAwNS0wMi0wOVQxOToyMzowMCAKTWVsIEthcm1hemluIGlzIHB1c2hpbmcgdG8gYWRkIFNpcml1cyBTYXRlbGxpdGUgc2VydmljZXMgdG8gaVBvZHMgLS0KYW4gaW50ZXJlc3RpbmcgaWRlYSwgaW5hc211Y2ggYXMgaXQgc2VlbXMgdG8gZGVmZWF0IHRoZSBwdXJwb3NlIG9mIGJvdGguClRoZSBpUG9kJ3MgdGhlIHRpbmllc3QgcG9zc2libGUgY29udGFpbmVyIGZvciB2YXN0IG11c2ljIGxpYnJhcmllcywgYW5kClNpcml1cyBpcyBhIHdheSB0byBnZXQgYXQgbG90cyBvZiBjb250ZW50IHdoZW4gc2FpZCBtdXNpYyBsaWJyYXJ5IGlzCnVuYXZhaWxhYmxlLiBPbiB0aGUgb3RoZXIgaGFuZCwgS2FybWF6aW4gYW5kIEpvYnMgYXJlIHR3byBvZiB0aGUKc21hcnRlc3QgZGVhbG1ha2VycyBhcm91bmQsIHNvIHRoZXkgbWlnaHQgZmluZCBhIHdheSB0byBzdHJ1Y3R1cmUgdGhpcwpvciBzcGluIGl0IHRvIHRoZSBiZW5lZml0IG9mIGV2ZXJ5b25lLiBNeSBtYWluIHN1c3BpY2lvbiBpcyB0aGF0IHRoaXMgaXMKS2FybWF6aW4gaG9waW5nIHRvIHNlZSB0aGUgcGhyYXNlICZxdW90O01lbCBLYXJtYXppbiwgQ0VPIFsmcXVvdDtUaGF0J3MgcmlnaHQsJnF1b3Q7Ck1lbCBzYXlzIHRvIGhpbXNlbGYsICZxdW90O0MtRS1mcmlnZ2luLSBPICEmcXVvdDtdIG9mIFNpcml1cyBTYXRlbGxpdGUgUmFkaW8uLi4mcXVvdDsKCgogaXJhLWNhbSAKID8/Pz8tPz8tPz9UMjM6NTg6MDAgClN0ZXZlIEpvYnMga25vd3MgYSBiYWQgaWRlYSB3aGVuIGhlJ3MgcGl0Y2hlZCBpdCwgZm9yIGV4YWN0bHkgdGhlCnJlYXNvbnMgeW91IHBvaW50IG91dC4gUGx1cywgYSBzYXRlbGxpdGUgcmVjZWl2ZXIgYnVybnMgYSBsb3Qgb2YgcG93ZXIsCmV2ZW4gaWYgaXQgY291bGQgYmUgbWFkZSB0aW55LgoKCiBCeXJuZSAKID8/Pz8tPz8tPz9UMTI6MDQ6MDAgCk9uIHRoZSBvdGhlciBoYW5kLCB0aGUgZ3V5IGhhcyBjb252aW5jZWQgc29tZSB2ZXJ5IHNtYXJ0IHBlb3BsZSB0bwpzcGVuZCBodWdlIHN1bXMgb24gc3R1cGlkIGlkZWFzIC0tIHRoZXJlIGlzbid0IG11Y2ggdGFsayBhYm91dCBpdCBub3csCmJ1dCBiYWNrIHdoZW4gaGlzIHJlcHV0YXRpb24gd2Fzbid0IHNvIGhvdCAobGF0ZSAnODBzKSwgbG90cyBvZgpqb3VybmFsaXN0cyB0YWxrZWQgYWJvdXQgdGhlICZxdW90O1N0ZXZlIEpvYnMgUmVhbGl0eSBEaXN0b3J0aW9uIEZpZWxkLiZxdW90OyBIZQpjb3VsZCBnZXQgcGVvcGxlIHRvIGlnbm9yZSBldmVyeSBzaW5nbGUgdGVjaG5pY2FsIG9ic3RhY2xlIHRvIGFuIGlkZWEsCmFuZCBpbnZlc3Qgb24gdGhlIGJhc2lzIG9mIHNvbWV0aGluZyBiZWF1dGlmdWxseSwgYnV0IHJpZGljdWxvdXNseSwKc2ltcGxlLiBCYXNpY2FsbHksIGhlIHNlbGxzIHRoZSBmdXR1cmU7IHRoZSBpUG9kIGFuZCB0aGUgTWFjIE1pbmkgYXJlCmp1c3QgdGltZXMgaGUgZ290IGx1Y2t5IGFuZCB0aGUgZnV0dXJlIGNhdWdodCB1cC4KCgogam9udGFpdCAKID8/Pz8tPz8tPz9UMTc6MzI6MDAgClllYS4KClllYS4KClllYS4KCkknbSB0aGUgcHJlc2lkZW50LiBPaCB5ZWEhCgpPaCB5ZWEhCgooeW91IGR1bWJhc3MpCgoKIGpvbnRhaXQgCiA/Pz8/LT8/LT8/VDE3OjQyOjAwIApjb21tZXJjaWFsIEEgdmlkZW8gb2YgYSBjb21tZXJjaWFsIGluIGNhc2Ugbm9ib2R5IGtub3dzIHdoYXQgSSZxdW90O20KdGFsa2luZyBhYm91dCA9KQoKPC9URVhUPgoKCjwvRE9DPg==</body>
  </SimpleSignal>
  <AnchorSet containedType="text-point"/>
  <RegionSet containedType="link-subordinates"/>
  <RegionSet containedType="rlink-subordinates"/>
  <RegionSet containedType="text-extent"/>
  <Analysis id="Ana2329" type="link-extent-set" role="link-extent-set">
    <AnnotationSet containedType="link-extent"/>
  </Analysis>
  <Analysis id="Ana2330" type="link-set" role="link-set">
    <AnnotationSet containedType="LINK"/>
  </Analysis>
  <Analysis id="Ana2331" type="place-set" role="place-set">
    <AnnotationSet containedType="PLACE"/>
  </Analysis>
  <Analysis id="Ana2332" type="rlink-extent-set" role="rlink-extent-set">
    <AnnotationSet containedType="rlink-extent"/>
  </Analysis>
  <Analysis id="Ana2333" type="rlink-set" role="rlink-set">
    <AnnotationSet containedType="RLINK"/>
  </Analysis>
  <Analysis id="Ana2334" type="signal-set" role="signal-set">
    <AnnotationSet containedType="SIGNAL"/>
  </Analysis>
</Corpus>

=== zekun-li/toponym_detection/spatialml/package/ace_2005_spatialML/data/MARKETVIEW_20050217.2115.aif.xml
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE Corpus SYSTEM "http://www.nist.gov/speech/atlas/aif.dtd">

<Corpus xmlns="http://www.nist.gov/speech/atlas" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://www.ukoln.ac.uk/interop-focus/activities/z3950/int_profile/bath/draft/stable1.html" id="Cor84" AIFVersion="1.1" type="spatialml" schemeLocation="http://callisto.mitre.org/maia/spatialml.maia.xml">
  <Metadata/>
  <SimpleSignal id="Sig84" type="text" mimeClass="text" mimeType="sgml" xlink:href="MARKETVIEW_20050217.2115.sgml.sgml" encoding="UTF-8" track="ALL" xlink:type="simple">
    <body encoding="Base64">PERPQz4KCiBNQVJLRVRWSUVXXzIwMDUwMjE3LjIxMTUgCiBXRUIgVEVYVCAKIDIwMDUtMDItMTdUMjE6MTU6MDAgCgoKQW4gQWlybGluZSBQYXNzZW5nZXIncyBCaWxsIG9mIFJpZ2h0cz8KCjxURVhUPgoKCiBCeXJuZSAKIDIwMDUtMDItMTdUMjE6MTU6MDAgCkhhcyB0aGUgRVUgb25jZSBhZ2FpbiBsb3N0IGl0cyBtaW5kPyBUaGUgb25lIGluZHVzdHJ5IGluIHdoaWNoIEV1cm9wZQppbmNvbnRyb3ZlcnRpYmx5IGJlYXRzIHRoZSBVUyBpcyB0aGVpciBhdmlhdGlvbiBpbmR1c3RyeSAsIHRoYW5rcyBtYWlubHkKdG8gdGhlIGZhY3QgdGhhdCB0aGVpciBsYXdtYWtlcnMgaGF2ZSBsZWZ0IHRoZSBvcGVyYXRpb24gb2YgdGhlIGluZHVzdHJ5CnVwIHRvIHRoZSBwZW9wbGUgd2hvIG93biBpdCwgYW5kIGxlZnQgcGFzc2VuZ2VyJ3MgcmlnaHRzIGluIHRoZSBoYW5kcyBvZgpjaG9vc3kgcGFzc2VuZ2Vycy4gQW5kIG5vdyB0aGV5J3JlIHJlYWR5IHRvICdmaXgnIHRoYXQgd2l0aCBhIG5ldwpwYWNrYWdlIG9mIGlsbC1hZHZpc2VkIHJ1bGVzIGNvbXBsZXRlbHkgY2hhbmdpbmcgdGhlIG5hdHVyZSBvZiBhaXJsaW5lcwouIEJlZm9yZSwgYSBwb3RlbnRpYWwgY3VzdG9tZXIgY291bGQgY2hvb3NlIGJldHdlZW4gYSBjb3N5LCBuZWFyLWNlcnRhaW4KcmlkZSBmcm9tIGFuIGV4cGVuc2l2ZSBjb21wYW55IG9yIGEgaHVzdGxlZCwgdW5jb21mb3J0YWJsZSwgYW5kIGFic3VyZGx5CmNoZWFwIG9uZSBmcm9tIGEgc21hbGxlciBjb21wZXRpdG9yLiBBbmQgbm93PyBOb3QgYSBjaGFuY2UuCgo8L1RFWFQ+CgoKPC9ET0M+</body>
  </SimpleSignal>
  <AnchorSet containedType="text-point">
    <Anchor id="Anc2971" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">200</Parameter>
      <SignalRef xlink:href="#Sig84" role="text" xlink:type="simple"/>
    </Anchor>
    <Anchor id="Anc2972" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">206</Parameter>
      <SignalRef xlink:href="#Sig84" role="text" xlink:type="simple"/>
    </Anchor>
    <Anchor id="Anc2973" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">234</Parameter>
      <SignalRef xlink:href="#Sig84" role="text" xlink:type="simple"/>
    </Anchor>
    <Anchor id="Anc2974" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">236</Parameter>
      <SignalRef xlink:href="#Sig84" role="text" xlink:type="simple"/>
    </Anchor>
  </AnchorSet>
  <RegionSet containedType="link-subordinates"/>
  <RegionSet containedType="rlink-subordinates"/>
  <RegionSet containedType="text-extent">
    <Region id="Reg1540" type="text-extent">
      <AnchorRef xlink:href="#Anc2972" role="end" xlink:type="simple"/>
      <AnchorRef xlink:href="#Anc2971" role="start" xlink:type="simple"/>
    </Region>
    <Region id="Reg1541" type="text-extent">
      <AnchorRef xlink:href="#Anc2974" role="end" xlink:type="simple"/>
      <AnchorRef xlink:href="#Anc2973" role="start" xlink:type="simple"/>
    </Region>
  </RegionSet>
  <Analysis id="Ana499" type="link-extent-set" role="link-extent-set">
    <AnnotationSet containedType="link-extent"/>
  </Analysis>
  <Analysis id="Ana500" type="link-set" role="link-set">
    <AnnotationSet containedType="LINK"/>
  </Analysis>
  <Analysis id="Ana501" type="place-set" role="place-set">
    <AnnotationSet containedType="PLACE">
      <Annotation id="Ann1540" type="PLACE">
        <RegionRef xlink:href="#Reg1540" role="text-extent" xlink:type="simple"/>
        <Content type="place-content">
          <Parameter type="string" unit="NULL_UNIT" role="CTV"/>
          <Parameter type="string" unit="NULL_UNIT" role="comment"/>
          <Parameter type="string" unit="NULL_UNIT" role="continent">EU</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="country"/>
          <Parameter type="string" unit="NULL_UNIT" role="county"/>
          <Parameter type="string" unit="NULL_UNIT" role="description"/>
          <Parameter type="string" unit="NULL_UNIT" role="form">NAM</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="gazref">IGDB:30064878</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="id">Pl-1</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="latLong"/>
          <Parameter type="string" unit="NULL_UNIT" role="mod"/>
          <Parameter type="string" unit="NULL_UNIT" role="nonLocUse"/>
          <Parameter type="string" unit="NULL_UNIT" role="predicative"/>
          <Parameter type="string" unit="NULL_UNIT" role="state"/>
          <Parameter type="string" unit="NULL_UNIT" role="type">CONTINENT</Parameter>
        </Content>
      </Annotation>
      <Annotation id="Ann1541" type="PLACE">
        <RegionRef xlink:href="#Reg1541" role="text-extent" xlink:type="simple"/>
        <Content type="place-content">
          <Parameter type="string" unit="NULL_UNIT" role="CTV"/>
          <Parameter type="string" unit="NULL_UNIT" role="comment"/>
          <Parameter type="string" unit="NULL_UNIT" role="continent"/>
          <Parameter type="string" unit="NULL_UNIT" role="country">US</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="county"/>
          <Parameter type="string" unit="NULL_UNIT" role="description"/>
          <Parameter type="string" unit="NULL_UNIT" role="form">NAM</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="gazref">IGDB:840</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="id">Pl-2</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="latLong"/>
          <Parameter type="string" unit="NULL_UNIT" role="mod"/>
          <Parameter type="string" unit="NULL_UNIT" role="nonLocUse"/>
          <Parameter type="string" unit="NULL_UNIT" role="predicative"/>
          <Parameter type="string" unit="NULL_UNIT" role="state"/>
          <Parameter type="string" unit="NULL_UNIT" role="type">COUNTRY</Parameter>
        </Content>
      </Annotation>
    </AnnotationSet>
  </Analysis>
  <Analysis id="Ana502" type="rlink-extent-set" role="rlink-extent-set">
    <AnnotationSet containedType="rlink-extent"/>
  </Analysis>
  <Analysis id="Ana503" type="rlink-set" role="rlink-set">
    <AnnotationSet containedType="RLINK"/>
  </Analysis>
  <Analysis id="Ana504" type="signal-set" role="signal-set">
    <AnnotationSet containedType="SIGNAL"/>
  </Analysis>
</Corpus>
