=== zekun-li/toponym_detection/spatialml/package/common_files/dtd/aif.dtd
<!-- 

A DTD for ATLAS Interchange Format [AIF], a means of interchanging
annotations. AIF has been developed following joint discussions with
Bird (LDC), Day (MITRE), Garofolo (NIST), Henderson (MITRE) and Laprun
(NIST).

Current maintainer: Chris Laprun [ chris.laprun@nist.gov ]

$Id: aif.dtd,v 1.22 2002/09/13 19:32:14 chris Exp $

-->

<!-- ** PARAMETER ENTITIES ** -->
<!ENTITY % MetadataDef SYSTEM "metadata.dtd"> %MetadataDef;

<!ENTITY % FeatureData "(Feature  | Parameter)+">

<!ENTITY % containerAtt "
    containedType NMTOKEN   #REQUIRED">

<!ENTITY % refAtt "    
    xlink:type    CDATA             #FIXED    'simple'
    xlink:href    CDATA             #REQUIRED
    role          NMTOKEN           #REQUIRED">

<!ENTITY % idAtt "
    id          ID       #REQUIRED
    type        NMTOKEN  #REQUIRED">

<!-- ** ELEMENTS ** -->
<!ELEMENT Corpus ( Metadata, (SimpleSignal | SignalGroup)*, AnchorSet*, RegionSet*, Analysis*)>
<!ATTLIST Corpus
    %idAtt;
    AIFVersion  CDATA    #FIXED    "1.1"
    xmlns       CDATA    #FIXED    "http://www.nist.gov/speech/atlas"
    xmlns:xlink CDATA    #FIXED    "http://www.w3.org/1999/xlink"
    schemeLocation CDATA #REQUIRED
>

<!ELEMENT Analysis ( Metadata?, AnnotationSet* )>
<!ATTLIST Analysis
    %idAtt;
    role        NMTOKEN  #REQUIRED
>

<!ELEMENT AnchorSet ( Anchor* )>
<!ATTLIST AnchorSet %containerAtt;>

<!ELEMENT AnnotationSet ( Annotation* )>
<!ATTLIST AnnotationSet %containerAtt;>

<!ELEMENT RegionSet ( Region* )>
<!ATTLIST RegionSet %containerAtt;>

<!ELEMENT SimpleSignal ( body )> <!-- changed Metadata? to body -->
<!ATTLIST SimpleSignal
    %idAtt;
    mimeClass   CDATA      #REQUIRED
    mimeType    CDATA      #REQUIRED
    encoding    CDATA      #REQUIRED
    xlink:type  CDATA      #FIXED        "simple"
    xlink:href  CDATA      #REQUIRED
    track       NMTOKEN    "ALL"
>

<!-- added body -->
<!ELEMENT body ( #PCDATA )>
<!ATTLIST body
    encoding    CDATA      #REQUIRED
>

<!ELEMENT SignalGroup ( Metadata?, SignalRef+ )>
<!ATTLIST SignalGroup %idAtt;>

<!ELEMENT Annotation ( (RegionRef | RegionDefinedByChildren), (Content | ContentDefinedByChildren), Children* )>
<!ATTLIST Annotation %idAtt;>

<!ELEMENT Content ( RegionRef? , (%FeatureData;)? )>
<!ATTLIST Content
    type       NMTOKEN    #REQUIRED
>

<!ELEMENT Feature %FeatureData;>
<!ATTLIST Feature
    role        NMTOKEN    #REQUIRED
    type        NMTOKEN    #REQUIRED     
>

<!ELEMENT Region 
    ( (AnchorRef | RegionRef | AnnotationRef)*, 
    (AnchorRefSet | RegionRefSet | AnnotationRefSet)* )>
<!ATTLIST Region %idAtt;>

<!ELEMENT Anchor ( Parameter+, SignalRef )>
<!ATTLIST Anchor %idAtt;>

<!ELEMENT Parameter ( #PCDATA )>
<!ATTLIST Parameter
    type        NMTOKEN     #REQUIRED 
    role        NMTOKEN     #REQUIRED    
    unit        NMTOKEN     #REQUIRED
>

<!ELEMENT AnchorRefSet ( AnchorRef* )>
<!ATTLIST AnchorRefSet %containerAtt;>

<!ELEMENT AnnotationRefSet ( AnnotationRef* )>
<!ATTLIST AnnotationRefSet %containerAtt;>

<!ELEMENT RegionRefSet ( RegionRef* )>
<!ATTLIST RegionRefSet %containerAtt;>

<!ELEMENT Children ( AnnotationRef* )>
<!ATTLIST Children %containerAtt;
  role        NMTOKEN #REQUIRED
>

<!ELEMENT ContentDefinedByChildren EMPTY>
<!ATTLIST ContentDefinedByChildren
   withContainedType NMTOKEN #REQUIRED
   withRole          NMTOKEN #REQUIRED
>

<!ELEMENT RegionDefinedByChildren EMPTY>
<!ATTLIST RegionDefinedByChildren
   withContainedType NMTOKEN #REQUIRED
   withRole          NMTOKEN #REQUIRED
>

<!ELEMENT RegionRef EMPTY>
<!ATTLIST RegionRef %refAtt;>

<!ELEMENT AnchorRef EMPTY>
<!ATTLIST AnchorRef %refAtt;>

<!ELEMENT AnnotationRef EMPTY>
<!ATTLIST AnnotationRef %refAtt;>

<!ELEMENT SignalRef EMPTY>
<!ATTLIST SignalRef %refAtt;>

=== zekun-li/toponym_detection/spatialml/mitre_spatialml_v1/data/CNN_ENG_20030820_172101.18.aif.xml
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE Corpus SYSTEM "http://www.nist.gov/speech/atlas/aif.dtd">

<Corpus xmlns="http://www.nist.gov/speech/atlas" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://www.ukoln.ac.uk/interop-focus/activities/z3950/int_profile/bath/draft/stable1.html" id="Cor14" AIFVersion="1.1" type="spatialml" schemeLocation="http://callisto.mitre.org/maia/spatialml.maia.xml">
  <Metadata/>
  <SimpleSignal id="Sig14" type="text" mimeClass="text" mimeType="sgml" xlink:href="CNN_ENG_20030820_172101.18" encoding="UTF-8" track="ALL" xlink:type="simple">
    <body encoding="Base64">PERPQz4NCg0KIENOTl9FTkdfMjAwMzA4MjBfMTcyMTAxLjE4IA0KIE5FV1MgU1RPUlkgDQogMjAwMy0wOC0yMCAxNzo1NDowOCANCg0KPFRFWFQ+DQoNCg0KY2FyYWNhcyBjZWxlYnJhdGlvbi4gdGVucyBvZiB0aG91c2FuZHMgb2YgcGVvcGxlIHBvdXJlZCBpbnRvIHRoZQ0Kc3RyZWV0cyBvZiB2ZW5lenVlbGEncyBjYXBpdGFsIHRvIG1hcmsgYW5vdGhlciBzdGVwIGZvcndhcmQgaW4gdGhlaXINCmJpZCB0byBkcml2ZSBwcmVzaWRlbnQgaHVnbyBjaGF2ZXogZnJvbSBwb3dlci4gb3Bwb3NpdGlvbiBsZWFkZXJzDQp0dXJuZWQgaW4gYWxtb3N0IDMgbWlsbGlvbiBzaWduYXR1cmVzIHdpdGggYSByZWZlcmVuZHVtIGVuZGluZyBoaXMNCnByZXNpZGVuY3kuIGNoYXZleiBrZWVwcyBmaWdodGluZyB0aGVtIHRvIHN0YXkgaW4gb2ZmaWNlLg0KDQo8L1RFWFQ+DQoNCg0KIDIwMDMtMDgtMjAgMTc6NTQ6MjMgDQoNCg0KPC9ET0M+</body>
  </SimpleSignal>
  <AnchorSet containedType="text-point">
    <Anchor id="Anc360" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">79</Parameter>
      <SignalRef xlink:href="#Sig14" role="text" xlink:type="simple"/>
    </Anchor>
    <Anchor id="Anc361" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">86</Parameter>
      <SignalRef xlink:href="#Sig14" role="text" xlink:type="simple"/>
    </Anchor>
    <Anchor id="Anc362" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">168</Parameter>
      <SignalRef xlink:href="#Sig14" role="text" xlink:type="simple"/>
    </Anchor>
    <Anchor id="Anc363" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">175</Parameter>
      <SignalRef xlink:href="#Sig14" role="text" xlink:type="simple"/>
    </Anchor>
    <Anchor id="Anc364" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">156</Parameter>
      <SignalRef xlink:href="#Sig14" role="text" xlink:type="simple"/>
    </Anchor>
    <Anchor id="Anc365" type="text-point">
      <Parameter type="char" unit="NULL_UNIT" role="char">165</Parameter>
      <SignalRef xlink:href="#Sig14" role="text" xlink:type="simple"/>
    </Anchor>
  </AnchorSet>
  <RegionSet containedType="link-subordinates">
    <Region id="Reg189" type="link-subordinates">
      <AnnotationRef xlink:href="#Ann186" role="source" xlink:type="simple"/>
      <AnnotationRef xlink:href="#Ann187" role="target" xlink:type="simple"/>
      <AnnotationRefSet containedType="PLACE"/>
    </Region>
  </RegionSet>
  <RegionSet containedType="path-subordinates"/>
  <RegionSet containedType="text-extent">
    <Region id="Reg185" type="text-extent">
      <AnchorRef xlink:href="#Anc361" role="end" xlink:type="simple"/>
      <AnchorRef xlink:href="#Anc360" role="start" xlink:type="simple"/>
    </Region>
    <Region id="Reg186" type="text-extent">
      <AnchorRef xlink:href="#Anc363" role="end" xlink:type="simple"/>
      <AnchorRef xlink:href="#Anc362" role="start" xlink:type="simple"/>
    </Region>
    <Region id="Reg187" type="text-extent">
      <AnchorRef xlink:href="#Anc365" role="end" xlink:type="simple"/>
      <AnchorRef xlink:href="#Anc364" role="start" xlink:type="simple"/>
    </Region>
  </RegionSet>
  <Analysis id="Ana79" type="link-extent-set" role="link-extent-set">
    <AnnotationSet containedType="link-extent"/>
  </Analysis>
  <Analysis id="Ana80" type="link-set" role="link-set">
    <AnnotationSet containedType="LINK">
      <Annotation id="Ann189" type="LINK">
        <RegionRef xlink:href="#Reg189" role="subordinates" xlink:type="simple"/>
        <Content type="link-content">
          <Parameter type="string" unit="NULL_UNIT" role="comment"/>
          <Parameter type="string" unit="NULL_UNIT" role="id">L-1</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="linkType">IN</Parameter>
        </Content>
      </Annotation>
    </AnnotationSet>
  </Analysis>
  <Analysis id="Ana81" type="path-extent-set" role="path-extent-set">
    <AnnotationSet containedType="path-extent"/>
  </Analysis>
  <Analysis id="Ana82" type="path-set" role="path-set">
    <AnnotationSet containedType="PATH"/>
  </Analysis>
  <Analysis id="Ana83" type="place-set" role="place-set">
    <AnnotationSet containedType="PLACE">
      <Annotation id="Ann185" type="PLACE">
        <RegionRef xlink:href="#Reg185" role="text-extent" xlink:type="simple"/>
        <Content type="place-content">
          <Parameter type="string" unit="NULL_UNIT" role="CTV"/>
          <Parameter type="string" unit="NULL_UNIT" role="comment"/>
          <Parameter type="string" unit="NULL_UNIT" role="continent"/>
          <Parameter type="string" unit="NULL_UNIT" role="country">VE</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="county"/>
          <Parameter type="string" unit="NULL_UNIT" role="description"/>
          <Parameter type="string" unit="NULL_UNIT" role="form">NAM</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="gazref">IGDB:19061543</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="id">Pl-1</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="latLong">10.500&#176;N 66.917&#176;W</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="mod"/>
          <Parameter type="string" unit="NULL_UNIT" role="nonLocUse"/>
          <Parameter type="string" unit="NULL_UNIT" role="state">M</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="type">PPLC</Parameter>
        </Content>
      </Annotation>
      <Annotation id="Ann186" type="PLACE">
        <RegionRef xlink:href="#Reg186" role="text-extent" xlink:type="simple"/>
        <Content type="place-content">
          <Parameter type="string" unit="NULL_UNIT" role="CTV"/>
          <Parameter type="string" unit="NULL_UNIT" role="comment"/>
          <Parameter type="string" unit="NULL_UNIT" role="continent"/>
          <Parameter type="string" unit="NULL_UNIT" role="country">VE</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="county"/>
          <Parameter type="string" unit="NULL_UNIT" role="description"/>
          <Parameter type="string" unit="NULL_UNIT" role="form">NOM</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="gazref">IGDB:19061543</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="id">Pl-2</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="latLong">10.500&#176;N 66.917&#176;W</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="mod"/>
          <Parameter type="string" unit="NULL_UNIT" role="nonLocUse"/>
          <Parameter type="string" unit="NULL_UNIT" role="state">M</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="type">PPLC</Parameter>
        </Content>
      </Annotation>
      <Annotation id="Ann187" type="PLACE">
        <RegionRef xlink:href="#Reg187" role="text-extent" xlink:type="simple"/>
        <Content type="place-content">
          <Parameter type="string" unit="NULL_UNIT" role="CTV"/>
          <Parameter type="string" unit="NULL_UNIT" role="comment"/>
          <Parameter type="string" unit="NULL_UNIT" role="continent"/>
          <Parameter type="string" unit="NULL_UNIT" role="country">VE</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="county"/>
          <Parameter type="string" unit="NULL_UNIT" role="description"/>
          <Parameter type="string" unit="NULL_UNIT" role="form">NAM</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="gazref">IGDB:19039685</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="id">Pl-3</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="latLong">8.000&#176;N 66.000&#176;W</Parameter>
          <Parameter type="string" unit="NULL_UNIT" role="mod"/>
          <Parameter type="string" unit="NULL_UNIT" role="nonLocUse"/>
          <Parameter type="string" unit="NULL_UNIT" role="state"/>
          <Parameter type="string" unit="NULL_UNIT" role="type">COUNTRY</Parameter>
        </Content>
      </Annotation>
    </AnnotationSet>
  </Analysis>
  <Analysis id="Ana84" type="signal-set" role="signal-set">
    <AnnotationSet containedType="SIGNAL"/>
  </Analysis>
</Corpus>
